###################################
# KitPvP plugin with other stuff! #
# Made by Exellanix               #
###################################

###############
#    MySQL    #
###############
Use-MySQL: false

database: kitpvp
ip: localhost
port: 0000
username: root
password: password

#######
# END #
#######
