main: me.exellanix.kitpvp.Main
version: 3.0
name: KitPvP
author: Exellanix
authors: [Mac_Genius]
description: The KitPvP plugin for ExellPvP
commands:
  kit:
      description: Gives a list of kits to choose!
      usage: /<command> 
      aliases: [kits, k, pvpkits, pvpkit]
  repair:
      desription: Repairs a players armor!
      usage: /<command>
